#Define the HTML content
html_content = """<!DOCTYPE html> 
<html> 
<head lang="mk"> 
<meta charset="utf-8">
<title>My HTML File</title> 
</head> 
<body> 
<h1>напомена</h1> 
<p>This is a html file generated by a Python script.</p> 
</body> 
</html> 
"""

# Write the HTML content to a file
with open("", "w", encoding="utf-8") as html_file:
    html_file.write(html_content)
#print("HTML file created successfully.")